repos:
  - repo: local
    hooks:
    - id: autoflake
      name: Autoflake
      entry: autoflake
      language: python
      types: [python]
      additional_dependencies: [autoflake]
      exclude: ^tests/fixtures
      args:
        - --remove-all-unused-imports
        - --expand-star-imports
        - --ignore-init-module-imports
        - -i
        - -r
  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3
      exclude: ^tests/fixtures
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
      exclude: ^tests/fixtures
  - repo: https://github.com/depop/pyorphans
    rev: 0.2.2
    hooks:
    - id: pyorphans
      args:
        - apigraph
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    - id: isort
      exclude: ^tests/fixtures
      args:
        - --filter-files
