# needed for python >= 3.6
sudo: required
dist: xenial
# ---
language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install pipenv
  - pipenv install --dev
  - pip install .
script:
  - if (( $(bc -l <<< "${TRAVIS_PYTHON_VERSION} < 3.8") )); then pytype waterloo/; fi
  - pytest -v tests/
