# needed for python >= 3.6
sudo: required
dist: xenial
cache: pip
# ---
language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install poetry
  - poetry install
script:
  - pytype -d import-error waterloo/
  - pytest -v tests/
