# needed for python >= 3.6
sudo: required
dist: xenial
# ---
language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install hypothesis
  - pip install pytype
  - pip install typing-extensions==3.7.4.1
  - pip install .
  # (note: pytest already available in travis, breaks if we install our own)
script:
  - pytype waterloo/
  - pytest tests/
