name:                waterloo-haskell
version:             0.1.0.0
github:              "value/waterloo-haskell"
license:             BSD3
author:              "value"
maintainer:          "value"
copyright:           "value"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/value/waterloo-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

# executables:
#   waterloo-haskell-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - waterloo-haskell

tests:
  waterloo-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - waterloo-haskell
    - megaparsec
    - megaparsec-tests
    - parser-combinators
    - QuickCheck
    - hspec
    - hspec-expectations
    - hspec-discover
    - hspec-megaparsec
    - text
